//! # `page_generation_covers` — **what `page_content_generation` actually
//! notices**, measured rather than assumed
//!
//! ## Why this test exists
//!
//! `pdfce-core`'s reply of 2026-08-31
//! (`reply_the_verbs_decomposition_is_gone_and_two_of_your_premises_were_wrong.md`)
//! offers this shell a cheap invalidation key:
//!
//! > *"Your `(page, edit_epoch)` cache key can go. `Pass 186.0` also shipped
//! > `EditSession::page_content_generation(page_index) -> u64` … comparing
//! > object counts means decomposing twice, comparing this means comparing two
//! > integers."*
//!
//! The prize is large and measured: this shell's own decomposition of the
//! operator's benchmark drawing takes **469 ms** for 129,758 objects and
//! 10,256 leaves (`page-objects-built page=0 objects=129758 leaves=10256
//! ms=469`, driven 2026-08-31). Today it is rebuilt on **every** `edit_epoch`
//! bump — including edits that cannot have touched page content at all, such
//! as authoring a form field, which is an `/Annots` change. That is the
//! operator's O74 complaint in its most expensive form.
//!
//! ## ★★★ Why a TEST and not a swap
//!
//! Because the failure mode of a wrong invalidation key is not a slow program.
//! `PageObjects` addresses content **by index**, so a stale model makes
//! `move_objects(page, &[7], …)` edit whatever object 7 is in the *wrong*
//! model — the engine's own words for this are *"silent corruption of the
//! operator's drawing, reported as success"*.
//!
//! ⇒ So before this shell trusts that number, it establishes exactly what the
//! number notices. Each test here is one dependency class, driven through the
//! real verbs, on a fixture built for it.
//!
//! ## ★★ The class this is really about
//!
//! The engine's reply says the memo's key is *"(page id, every `/Contents`
//! entry with its staged span, the effective `/Resources`)"* — and that the
//! forms a page descends into are kept **beside** the key rather than in it,
//! *"because which forms a page paints is an OUTPUT of the decomposition, not
//! an input to it"*.
//!
//! `page_content_generation` is documented as the digest of *"the same key the
//! memo uses"*. If that means the key **without** the form set, then an edit
//! inside a form XObject moves nothing this shell could see — and a shell that
//! had swapped its cache key would keep a stale model after every such edit.
//!
//! That case is not reachable from this shell's UI today (in-form editing is
//! refused, `Refusal::InsideForm`), and `pdfce-core` Pass 188.0 shipped the six
//! verbs that will make it reachable. **This test is what tells us which order
//! those two things may be done in.**

use pdfce_core::edit::EditSession;

/// The form fixture: one page object (a form), three path leaves inside it.
/// Generated by `tools/gen-form-xobject-fixture.py`.
fn form_fixture() -> pdfce_core::document::Document {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/form-xobject.pdf"
    );
    pdfce_core::document::Document::load(std::path::Path::new(path))
        .expect("fixture form-xobject.pdf must load — run tools/gen-form-xobject-fixture.py")
}

/// A page with ordinary content, for the classes that do not need a form.
fn plain_fixture() -> pdfce_core::document::Document {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/a1-titleblock.pdf"
    );
    pdfce_core::document::Document::load(std::path::Path::new(path))
        .expect("fixture a1-titleblock.pdf must load")
}

/// ★★★ **A content edit moves it.** The baseline: without this the number
/// would be useless in the other direction, and a cache keyed on it would
/// never rebuild.
#[test]
fn a_content_edit_moves_the_generation() {
    let mut session = EditSession::new(plain_fixture());
    let before = session
        .page_content_generation(0)
        .expect("page 0 has a generation");

    // The cheapest real content edit: move an object by a point.
    let objects = session
        .page_objects(0)
        .expect("page 0 decomposes")
        .objects
        .len();
    assert!(objects > 0, "the fixture must have something to move");
    session
        .move_objects(0, &[0], 1.0, 0.0)
        .expect("moving object 0 by one point must succeed");

    let after = session
        .page_content_generation(0)
        .expect("page 0 still has a generation");
    assert_ne!(
        before, after,
        "★ a content edit must move the generation, or a cache keyed on it would serve a pre-edit model for ever"
    );
}

/// ★★★ **AN EDIT INSIDE A FORM DOES NOT MOVE IT — measured 2026-08-31, and
/// this test is the tripwire on that.**
///
/// Asked as *"does the generation cover a form-stream rewrite?"* and answered
/// **no**: `move_node_in_form` succeeded, rewrote one invocation, and the
/// digest was identical either side —
///
/// ```text
/// before 9733417638757333672
/// after  9733417638757333672
/// ```
///
/// which is consistent with the engine's own account of its memo: the
/// descended-form set is kept **beside** the key *"because which forms a page
/// paints is an OUTPUT of the decomposition, not an input to it"*, and
/// `page_content_generation` digests the key alone.
///
/// ## What this shell does about it
///
/// 1. Keys its decomposition cache on the generation **and** a counter of its
///    own that the in-form verbs bump — a workaround, filed as one, per
///    decision 058.
/// 2. Writes this test **inverted**: it asserts the limitation, so the day the
///    engine closes it the test goes red and says what to delete.
///    `engine_overlay_skew` is the precedent — three tripwires, all three fired
///    within a day of the fix, and inverting them took minutes.
///
/// ★ What it does NOT do is weaken to *"the generation may or may not move"*.
/// A test that accepts both answers has stopped being a measurement.
#[test]
fn an_edit_inside_a_form_does_not_move_the_generation() {
    let mut session = EditSession::new(form_fixture());
    let model = session.page_objects(0).expect("page 0 decomposes");
    let leaves = model.leaves.len();
    assert!(
        leaves >= 1,
        "the fixture must decompose to leaves — `page_objects` returned none, \
         which is the pre-Pass-188.0 behaviour and means the engine is too old \
         for this test to mean anything"
    );
    // The first leaf is a path (the fixture paints three strokes), so the node
    // verbs apply to it.
    let editable = model.leaves.iter().filter(|l| l.is_editable()).count();
    assert!(
        editable >= 1,
        "the fixture's leaves must be paths — `is_editable` was a hard `false` \
         for every leaf before Pass 188.0"
    );
    drop(model);

    let before = session
        .page_content_generation(0)
        .expect("page 0 has a generation");

    // Move one node of the first editable leaf. The coordinates are page
    // space, per the engine's contract for the `*_in_form` verbs.
    let outcome =
        session.move_node_in_form(0, 0, 0, pdfce_core::vector::Point { x: 60.0, y: 60.0 });
    let outcome = outcome.expect("moving a node inside a form must succeed on Pass 188.0+");
    assert!(
        outcome.invocations > 0,
        "the verb must have rewritten at least one invocation: {outcome:?}"
    );

    let after = session
        .page_content_generation(0)
        .expect("page 0 still has a generation");
    assert_eq!(
        before, after,
        "★★★ THE ENGINE HAS FIXED IT — the generation now moves for an edit inside a form XObject.
         Do three things: invert this assertion to `assert_ne!`; delete the shell-side counter that exists only because this was true (grep `form_edits`); and close the request in the channel, saying it was measured here.
         Until then this IS the limitation, stated as a test rather than as a comment, because only one of the two is executed."
    );
}

/// ★★ **An annotation-only edit does NOT move it** — which is the whole prize.
///
/// Authoring a form field or a markup changes `/Annots`, never the page's
/// content stream. Today this shell rebuilds its 469 ms decomposition anyway,
/// because `edit_epoch` cannot tell the two apart. If the generation holds
/// still here, the rebuild can be skipped — and that is the operator's O74
/// complaint answered at its most expensive point.
#[test]
fn an_annotation_edit_does_not_move_the_generation() {
    let mut session = EditSession::new(plain_fixture());
    let before = session
        .page_content_generation(0)
        .expect("page 0 has a generation");

    // ★ Built through the shell's own pen helper rather than as a literal, for
    // the reason `apply::tests` gives for the same call: the spec's fields are
    // `#[non_exhaustive]`-adjacent in practice — a variant gaining a field
    // breaks a literal here and not the shell — and the helper is what the
    // operator's gesture actually produces.
    let spec = pdfce_gui::canvas::markup::spec_default_pen(
        pdfce_gui::canvas::markup::MarkupKind::Rectangle,
        &pdfce_gui::canvas::markup::Geometry::Band {
            start: (50.0, 50.0),
            end: (150.0, 120.0),
        },
    )
    .expect("a band is the Rectangle kind's own geometry");
    session
        .add_markup(0, &spec)
        .expect("adding a square markup must succeed");

    let after = session
        .page_content_generation(0)
        .expect("page 0 still has a generation");
    assert_eq!(
        before, after,
        "an annotation is not page content, so a decomposition cache has \
         nothing to rebuild — if this fails, the generation is coarser than \
         advertised and the 469 ms rebuild cannot be skipped after all"
    );
}
