//! # icons::assets — the icon set itself, and its provenance record
//!
//! **Generated content.** Every constant below embeds one file of
//! `src/icons/assets/*.svg`, which are byte-for-byte copies of the salvage
//! source's `D:\Dev\pdfce\crates\pdfce-gui\assets\icons\*.svg` — XML
//! rationale comments included. Nothing was retyped, reformatted or
//! "tidied": each asset's own comment is the primary record of what the
//! glyph depicts and which neighbouring glyph it was drawn to stay
//! distinguishable from, and a paraphrase would lose exactly the part that
//! is expensive to re-derive.
//!
//! ## ★ Why the art lives in `src/icons/assets/` rather than a top-level
//! ## `crates/pdfce-gui/assets/`
//!
//! The salvage source read its art with
//! `include_str!("../assets/icons/<name>.svg")` — a sibling directory of
//! `src/`. Here the same `include_str!` reaches a directory *inside* the
//! icon module. Two reasons:
//!
//! 1. **This module's write territory is `src/icons/`.** The rebuild runs
//!    several agents in parallel over one tree, and the boundaries between
//!    them are directories. Creating `crates/pdfce-gui/assets/` would put
//!    art outside the territory the icon work owns.
//! 2. **Co-location.** The art, the catalogue that names it, the parser that
//!    reads it and the painter that draws it are one subject. A reader who
//!    opens `src/icons/` sees all of it.
//!
//! `include_str!` — rather than a runtime file read — is carried across
//! unchanged, and its reason is unchanged: pdfce ships single-folder
//! portable, so the executable must not depend on an `assets/` directory
//! travelling beside it. The whole set is 34 KB of text and an icon that
//! fails to load at startup is not a failure mode worth having.
//!
//! ## ★ Why the SVG text is NOT inlined into Rust source
//!
//! The obvious alternative — a `const FOLDER: &str = r##"<svg …>"##;` with
//! the markup inline — was implemented first and then **withdrawn**,
//! because it fails `tools/gates/check-ui-strings.sh` on 138 lines and
//! cannot be exempted.
//!
//! That gate is a line-oriented scanner over `.rs` files looking for string
//! literals containing whitespace, which is its proxy for "prose that
//! belongs in the ui-text catalog". Almost every line of an SVG asset trips
//! it, because SVG *attribute values* are quoted strings full of spaces:
//! `viewBox="0 0 48 48"`, `d="M14 10h10M19 10v28"`. Its escape hatch is a
//! `// ui-text-exempt:` marker on the offending line or in the comment block
//! immediately above it — and neither can reach these lines, because they
//! are **inside a raw string**: a marker written there would become part of
//! the asset and be handed to the SVG parser.
//!
//! Keeping the art in `.svg` files is not a workaround for that gate; it is
//! the arrangement that makes the gate's question meaningful. XML markup is
//! not Rust source and should not be scanned as though it were. The finding
//! is recorded here because the inline form *looks* simpler and someone will
//! propose it again.
//!
//! ## ★ Regenerating
//!
//! The `.svg` files are copied from the salvage source; the constants below
//! are produced mechanically from the directory listing. If the set gains an
//! asset, drop the `.svg` in and add a constant here — **and add the
//! matching [`super::Icon`] variant to [`super::Icon::ALL`]**, or it ships
//! unverified (see `super::tests::every_icon_parses`).
//!
//! ---
//!
//! # Provenance
//!
//! Carried across from the salvage source's `assets/icons/PROVENANCE.md`,
//! which `docs/ui_specs/icon-set-and-toolbar.md` §7.2 required before any
//! art was bundled: the provenance of this set had to be **confirmed, not
//! assumed**. That record is a licensing artefact, so it travels with the
//! art it describes.
//!
//! ## §1 — Operator confirmation (the licensing question, closed)
//!
//! The ui-spec flagged an open question: were `D:\Dev\ScripTree\icons\*.svg`
//! drawn from scratch for ScripTree, or adapted from a third-party icon pack
//! (Feather, Lucide, Font Awesome, …) whose own licence would then travel
//! with them into pdfce's asset tree?
//!
//! Answered directly by the operator (Ken), 2026-08-02, verbatim:
//!
//! > "Scriptree icons are mine, use from it what makes sense and create new
//! > ones in its style when necessary, try to make them close to what
//! > inkscape and Adobe use for similar commands without running into
//! > copyright issues."
//!
//! Consequences, all of them binding on this module:
//!
//! * The ScripTree source art is the operator's own work. He owns both
//!   projects, so no third-party licence travels with the copied files and
//!   nothing here needs an upstream attribution entry.
//! * pdfce's own licence is MIT; these assets ship under it like the rest of
//!   the tree.
//! * `THIRD_PARTY_LICENSES.md` is unaffected — it is generated by
//!   `cargo-about` from the **dependency** set, and this set adds zero
//!   dependencies (see §6).
//!
//! ## §2 — The metaphor-not-artwork rule (binding on every future icon)
//!
//! The operator's instruction — *"try to make them close to what inkscape
//! and Adobe use for similar commands without running into copyright
//! issues"* — draws the line this module is held to:
//!
//! * **Allowed: metaphor-level resemblance.** A magnifier means zoom. A
//!   curved arrow means undo. Scissors mean split. Corner brackets mean fit
//!   to frame. These are industry conventions with no single author, and
//!   matching them is what makes a toolbar legible to someone arriving from
//!   Acrobat or Inkscape.
//! * **Forbidden: asset-level copying.** No tracing, no importing, no
//!   "adapting" of any Adobe or Inkscape SVG, icon font, or screenshot.
//!   Every glyph here was constructed from primitives (rectangles, circles,
//!   line segments, arcs), and every asset's embedded comment says which
//!   concept it depicts.
//! * This mirrors the standing rule that Acrobat and Inkscape are
//!   **behavioural** references only, never sources of GUI structure or art.
//!
//! This rule is *stricter* than copyright law strictly requires for simple
//! geometric glyphs. That is deliberate: it removes the question entirely
//! rather than leaving a judgement call in a file nobody will re-examine.
//!
//! ## §3 — Style contract (every asset here obeys it)
//!
//! ```xml
//! <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" fill="none" aria-hidden="true">
//!   <!-- Generic <concept> shape — placeholder, not a vendor trademark logo -->
//!   <path|rect|circle … stroke="currentColor" stroke-width="2.5"
//!         stroke-linecap="round" stroke-linejoin="round"/>
//! </svg>
//! ```
//!
//! * **48×48 viewBox**, content inset ~6–8 units from every edge. That edge
//!   length is [`super::svg::VIEWBOX`], and every coordinate is in it.
//! * **`fill="none"`, `stroke="currentColor"`** — pure outline, no baked
//!   colour. This is the property the whole pipeline rests on: one raster per
//!   icon, tinted per theme and per widget state at draw time. An asset with
//!   a hardcoded colour would break light/dark theming *structurally*, not
//!   just cosmetically.
//! * **`stroke-width="2.5"`**, round caps and joins throughout.
//! * A comment naming the concept and disclaiming trademark risk.
//!
//! ### The two deliberate exceptions
//!
//! `redact.svg` is the only asset with a **filled** shape
//! (`fill="currentColor"` on the redaction bar). ui-spec §8.1 makes this an
//! explicit, rule-based exception, not style drift: a solid bar is what
//! redaction actually leaves behind, and an outline-only glyph would
//! visually understate a feature that irreversibly removes content. **A
//! future icon audit must not "fix" it back to an outline.**
//! `super::tests::redaction_is_the_only_filled_icon` asserts both halves —
//! that redaction is filled and that nothing else is.
//!
//! `shape-highlight.svg` uses `stroke-width="1"` for its 45° hatch. Also
//! deliberate (ui-spec §3.3): the hatch is a *texture* standing in for
//! translucent highlighter colour, not a contour, and at 2.5 it would fill
//! the band solid and read as redaction.
//!
//! ## §4 — File-by-file origin
//!
//! **Copied verbatim from `D:\Dev\ScripTree\icons\`** (the operator's own
//! art), byte for byte apart from the filename. Renamed to pdfce's **role**
//! rather than ScripTree's shape name so a future re-draw changes one asset
//! and no call site:
//!
//! | Here | ScripTree source | Role |
//! |---|---|---|
//! | `folder.svg` | `icon-folder.svg` | Open **and** Font folders — one asset, two roles |
//! | `document.svg` | `icon-document.svg` | Properties |
//! | `edit.svg` | `icon-edit.svg` | Edit Text |
//! | `tool.svg` | `icon-tool.svg` | Tools |
//! | `ruler.svg` | `icon-ruler.svg` | Measure |
//! | `link.svg` | `icon-link.svg` | Combine files… |
//! | `scissors.svg` | `icon-scissors.svg` | Split this document… |
//! | `upload.svg` | `icon-upload.svg` | Insert pages from a file… |
//!
//! **Derived from a ScripTree file** (geometry reused, elements added):
//!
//! | Here | Derived from | What changed |
//! |---|---|---|
//! | `zoom-out.svg` | `icon-search.svg` | Magnifier circle and handle reused verbatim; a minus bar added inside |
//! | `zoom-in.svg` | `icon-search.svg` | Same base, plus a cross instead of a bar |
//!
//! **Authored new for pdfce, in the §3 contract** — everything else. Each
//! asset's embedded XML comment carries that glyph's own construction note
//! and, where it has one, the distinction it is drawn to preserve against a
//! neighbouring glyph. Those notes are the reason the files were copied
//! verbatim rather than re-emitted.
//!
//! ## §5 — Deviations from the ui-spec, recorded
//!
//! The standing convention is that the engineer implements a UI spec and
//! deviates only with a recorded reason. Six:
//!
//! 1. **`edit-objects.svg` is an addition the spec does not cover.** The
//!    ui-spec was written 2026-08-01 and audited the toolbar as it then
//!    stood; the "Obj" vector-edit toggle shipped afterwards. Its metaphor
//!    (a path with draggable nodes) is chosen to collide with nothing: not
//!    `edit.svg`'s pencil (page **text**), not `markup.svg`'s shapes
//!    (annotation **authoring**).
//! 2. **Icon size is 16 pt, not the 18–20 px ui-spec §4.1 suggests.** That
//!    paragraph contradicts itself; the reasoning is repeated in full at
//!    [`super::ICON_PTS`].
//! 3. **The rail's keyboard reorder arrows kept their Unicode glyphs** in
//!    the salvage source, rather than inventing art the spec had not
//!    reviewed. `chevron-up.svg` was later authored anyway, when those
//!    glyphs were VERIFIED tofu in the running build.
//! 4. **`bookmarks.svg`, `layers.svg`, `signatures.svg` are additions the
//!    spec does not cover** — same situation as #1. All three panels shipped
//!    with **no operator-reachable control at all**: a pane subject, a panel
//!    body, and nothing to click. `signatures.svg` carries a constraint
//!    beyond style — it is deliberately **not** a seal, badge, shield or
//!    checkmark, because each of those reads as VALIDATED and pdfce performs
//!    no cryptographic verification whatsoever. An icon is a claim too.
//! 5. **`fonts.svg` and `show-points.svg` are further additions of the same
//!    kind.** `fonts.svg`'s constraint is the mirror of `signatures.svg`'s:
//!    the Fonts panel is strictly read-only, so borrowing `add-text.svg`'s
//!    I-beam-plus or `edit.svg`'s pencil would have had the glyph promise an
//!    editing capability the panel does not have.
//! 6. **`form-field.svg`, `back.svg`, `close.svg`, `search.svg`,
//!    `chevron-up.svg` and `chevron-down.svg` were authored under the
//!    operator's 2026-08-06 ruling** that a missing glyph is **created** as
//!    part of the work rather than the feature reworded around it. The last
//!    four each replace a text character that was verified to have no face
//!    in the shipped font stack — `←` (U+2190), `✕` (U+2715), `▲` (U+25B2)
//!    and `▾` (U+25BE) — and so rendered as a tofu box on real controls.
//!
//! ## §6 — Rendering, and why no new dependency appears here
//!
//! These SVGs are **not** rasterized by any SVG library. [`super::svg`]
//! parses the subset of the path/rect/circle grammar these files use and
//! strokes it with `tiny-skia`, which is already reachable as
//! `pdfce_render::tiny_skia`. Zero Cargo dependencies were added for this
//! icon set — in particular `resvg`/`usvg` (MPL-2.0) was considered and
//! **rejected by the operator**, and pre-rasterizing to PNG at build time
//! was rejected because it bakes in a resolution.
//!
//! Practical consequence for anyone editing an asset: the parser refuses
//! anything outside its subset rather than guessing, and `super::tests`
//! parses and rasterizes every asset. **A new or edited icon that uses
//! `<g>`, `<defs>`, a `transform`, a gradient, CSS, or an unsupported
//! `stroke-linecap` value will fail `cargo test`, not fail silently at
//! runtime.**

/// `add-text.svg` — the art for [`super::Icon::AddText`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const ADD_TEXT: &str = include_str!("assets/add-text.svg");

/// `back.svg` — the art for [`super::Icon::Back`].
///
/// Authored for pdfce in the header §3 style contract — replaces the tofu `←` (U+2190).
pub(super) const BACK: &str = include_str!("assets/back.svg");

/// `bookmarks.svg` — the art for [`super::Icon::Bookmarks`].
///
/// Authored for pdfce in the header §3 style contract — header §5 addition #4.
pub(super) const BOOKMARKS: &str = include_str!("assets/bookmarks.svg");

/// `chevron-down.svg` — the art for [`super::Icon::ChevronDown`].
///
/// Authored for pdfce in the header §3 style contract — replaces the tofu `▾` (U+25BE).
pub(super) const CHEVRON_DOWN: &str = include_str!("assets/chevron-down.svg");

/// `chevron-left.svg` — the art for [`super::Icon::ChevronLeft`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const CHEVRON_LEFT: &str = include_str!("assets/chevron-left.svg");

/// `chevron-right.svg` — the art for [`super::Icon::ChevronRight`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const CHEVRON_RIGHT: &str = include_str!("assets/chevron-right.svg");

/// `chevron-up.svg` — the art for [`super::Icon::ChevronUp`].
///
/// Authored for pdfce in the header §3 style contract — replaces the tofu `▲` (U+25B2).
pub(super) const CHEVRON_UP: &str = include_str!("assets/chevron-up.svg");

/// `close.svg` — the art for [`super::Icon::Close`].
///
/// Authored for pdfce in the header §3 style contract — replaces the tofu `✕` (U+2715).
pub(super) const CLOSE: &str = include_str!("assets/close.svg");

/// `comment.svg` — the art for [`super::Icon::Comment`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const COMMENT: &str = include_str!("assets/comment.svg");

/// `copy.svg` — the art for [`super::Icon::Copy`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const COPY: &str = include_str!("assets/copy.svg");

/// `document.svg` — the art for [`super::Icon::Properties`].
///
/// Copied **verbatim** from ScripTree's `icon-document.svg` (the operator's own art; header §4).
pub(super) const DOCUMENT: &str = include_str!("assets/document.svg");

/// `edit-objects.svg` — the art for [`super::Icon::EditObjects`].
///
/// Authored for pdfce in the header §3 style contract — header §5 addition #1.
pub(super) const EDIT_OBJECTS: &str = include_str!("assets/edit-objects.svg");

/// `edit.svg` — the art for [`super::Icon::EditText`].
///
/// Copied **verbatim** from ScripTree's `icon-edit.svg` (the operator's own art; header §4).
pub(super) const EDIT: &str = include_str!("assets/edit.svg");

/// `fit-page.svg` — the art for [`super::Icon::FitPage`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const FIT_PAGE: &str = include_str!("assets/fit-page.svg");

/// `fit-width.svg` — the art for [`super::Icon::FitWidth`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const FIT_WIDTH: &str = include_str!("assets/fit-width.svg");

/// `folder.svg` — the art for [`super::Icon::Open`], [`super::Icon::FontFolders`].
///
/// Copied **verbatim** from ScripTree's `icon-folder.svg` (the operator's own art; header §4). One asset, two roles — see [`super::Icon::Open`].
pub(super) const FOLDER: &str = include_str!("assets/folder.svg");

/// `fonts.svg` — the art for [`super::Icon::Fonts`].
///
/// Authored for pdfce in the header §3 style contract — header §5 addition #5.
pub(super) const FONTS: &str = include_str!("assets/fonts.svg");

/// `form-field.svg` — the art for [`super::Icon::FormField`].
///
/// Authored for pdfce in the header §3 style contract — header §5 addition #6.
pub(super) const FORM_FIELD: &str = include_str!("assets/form-field.svg");

/// `keyboard.svg` — the art for [`super::Icon::Keyboard`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const KEYBOARD: &str = include_str!("assets/keyboard.svg");

/// `layers.svg` — the art for [`super::Icon::Layers`].
///
/// Authored for pdfce in the header §3 style contract — header §5 addition #4.
pub(super) const LAYERS: &str = include_str!("assets/layers.svg");

/// `link.svg` — the art for [`super::Icon::Combine`].
///
/// Copied **verbatim** from ScripTree's `icon-link.svg` (the operator's own art; header §4). Its `a6 6 0 008 8` packed arc flags are the reason [`super::svg`]'s lexer reads a flag as one character.
pub(super) const LINK: &str = include_str!("assets/link.svg");

/// `markup.svg` — the art for [`super::Icon::Markup`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const MARKUP: &str = include_str!("assets/markup.svg");

/// `redact.svg` — the art for [`super::Icon::Redact`].
///
/// Authored for pdfce in the header §3 style contract — the set's ONE filled glyph, an explicit rule-based exception (header §3).
pub(super) const REDACT: &str = include_str!("assets/redact.svg");

/// `redo.svg` — the art for [`super::Icon::Redo`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const REDO: &str = include_str!("assets/redo.svg");

/// `rotate-ccw.svg` — the art for [`super::Icon::RotateCcw`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const ROTATE_CCW: &str = include_str!("assets/rotate-ccw.svg");

/// `rotate-cw.svg` — the art for [`super::Icon::RotateCw`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const ROTATE_CW: &str = include_str!("assets/rotate-cw.svg");

/// `ruler.svg` — the art for [`super::Icon::Measure`].
///
/// Copied **verbatim** from ScripTree's `icon-ruler.svg` (the operator's own art; header §4).
pub(super) const RULER: &str = include_str!("assets/ruler.svg");

/// `save.svg` — the art for [`super::Icon::Save`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const SAVE: &str = include_str!("assets/save.svg");

/// `scissors.svg` — the art for [`super::Icon::Split`].
///
/// Copied **verbatim** from ScripTree's `icon-scissors.svg` (the operator's own art; header §4).
pub(super) const SCISSORS: &str = include_str!("assets/scissors.svg");

/// `search.svg` — the art for [`super::Icon::Search`].
///
/// Authored for pdfce in the header §3 style contract — the unmarked lens of the magnifier family.
pub(super) const SEARCH: &str = include_str!("assets/search.svg");

/// `shape-arrow.svg` — the art for [`super::Icon::ShapeArrow`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const SHAPE_ARROW: &str = include_str!("assets/shape-arrow.svg");

/// `shape-ellipse.svg` — the art for [`super::Icon::ShapeEllipse`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const SHAPE_ELLIPSE: &str = include_str!("assets/shape-ellipse.svg");

/// `shape-highlight.svg` — the art for [`super::Icon::ShapeHighlight`].
///
/// Authored for pdfce in the header §3 style contract — the one asset with a 1-unit stroke (its 45° hatch is a texture, not a contour).
pub(super) const SHAPE_HIGHLIGHT: &str = include_str!("assets/shape-highlight.svg");

/// `shape-rect.svg` — the art for [`super::Icon::ShapeRect`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const SHAPE_RECT: &str = include_str!("assets/shape-rect.svg");

/// `show-points.svg` — the art for [`super::Icon::ShowPoints`].
///
/// Authored for pdfce in the header §3 style contract — header §5 addition #5.
pub(super) const SHOW_POINTS: &str = include_str!("assets/show-points.svg");

/// `sidebar.svg` — the art for [`super::Icon::Sidebar`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const SIDEBAR: &str = include_str!("assets/sidebar.svg");

/// `signatures.svg` — the art for [`super::Icon::Signatures`].
///
/// Authored for pdfce in the header §3 style contract — header §5 addition #4, and emphatically not a seal, badge, shield or checkmark.
pub(super) const SIGNATURES: &str = include_str!("assets/signatures.svg");

/// `stamp.svg` — the art for [`super::Icon::Stamp`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const STAMP: &str = include_str!("assets/stamp.svg");

/// `text-freetext.svg` — the art for [`super::Icon::TextFreeText`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const TEXT_FREETEXT: &str = include_str!("assets/text-freetext.svg");

/// `text-sticky.svg` — the art for [`super::Icon::TextSticky`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const TEXT_STICKY: &str = include_str!("assets/text-sticky.svg");

/// `text.svg` — the art for [`super::Icon::Text`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const TEXT: &str = include_str!("assets/text.svg");

/// `tool.svg` — the art for [`super::Icon::Tools`].
///
/// Copied **verbatim** from ScripTree's `icon-tool.svg` (the operator's own art; header §4).
pub(super) const TOOL: &str = include_str!("assets/tool.svg");

/// `undo.svg` — the art for [`super::Icon::Undo`].
///
/// Authored for pdfce in the header §3 style contract.
pub(super) const UNDO: &str = include_str!("assets/undo.svg");

/// `upload.svg` — the art for [`super::Icon::InsertPages`].
///
/// Copied **verbatim** from ScripTree's `icon-upload.svg` (the operator's own art; header §4).
pub(super) const UPLOAD: &str = include_str!("assets/upload.svg");

/// `zoom-in.svg` — the art for [`super::Icon::ZoomIn`].
///
/// Derived from ScripTree's `icon-search.svg`: the same magnifier, plus a cross in the lens (header §4).
pub(super) const ZOOM_IN: &str = include_str!("assets/zoom-in.svg");

/// `zoom-out.svg` — the art for [`super::Icon::ZoomOut`].
///
/// Derived from ScripTree's `icon-search.svg`: the same magnifier, plus a minus bar in the lens (header §4).
pub(super) const ZOOM_OUT: &str = include_str!("assets/zoom-out.svg");
