#!/usr/bin/env python3
"""Build the pdfceGUI portable distribution into ``D:\\builds``.

WHY THIS EXISTS
===============

Operator request, 2026-08-13: *"When complete compile integrated with
pdfce in d:\\builds as a single exe like pdfce does. ... Basically I want
this to get to where I can use it to replace acrobat reader first."*

"Integrated with pdfce" needed no fold-in, and that is the single most
important fact about this script. `crates/pdfce-gui` depends on
`pdfce-core` and `pdfce-render` **by path** into `D:\\Dev\\pdfce` (see the
workspace root manifest, and PROJECT_PLAN.md §2). Rust links those
statically. So `cargo build --release -p pdfce-gui` in THIS workspace
already produces one self-contained executable carrying pdfce's engine
— the integration the request asks for is a property of the dependency
graph, not a merge that has to happen first.

That matters because the alternative reading — fold the new shell into
`D:\\Dev\\pdfce` and package from there — would have shipped a REGRESSION.
`FEATURES.md` § "Not salvaged yet" lists measure, redaction, settings
and text editing as still living only in the old shell. Replacing that
shell today to get one exe would trade four working capabilities for a
packaging convenience. Shipping from here costs nothing and keeps the
old build intact and installable beside it.

WHAT IT PRODUCES
================

``D:\\builds\\pdfcegui-<YYYYMMDD-HHMM>-<engine>-<shell>[-dirty][-enginedirty]\\``

    pdfce-gui.exe            the new shell, with pdfce's engine linked in
    LICENSE                  MIT
    THIRD_PARTY_LICENSES.md  generated by cargo-about, never hand-edited
    README.md                the project README
    FEATURES.md              what works today and what does not
    BUILD-INFO.txt           identity, verification state, what to try

`THIRD_PARTY_LICENSES.md` is not a courtesy. `pdfce-gui.exe` links
`pdfce-core` and `pdfce-render` statically, and those crates embed
third-party font faces and data tables with `include_bytes!` — so the
binary redistributes work whose licences require their notices to travel
with it. `cargo-about` covers the Cargo crates; the template's
hand-written epilogue covers the rest. See
`tools/gates/check-shipped-assets.py`, which fails if this file is not in
`PAYLOAD_DOCS` or has drifted from `about.hbs`.

The same attributions are reachable inside the program at
File ▸ pdfce ▸ About pdfce, because a GUI operator who launched from a
shortcut may never open this folder.

`FEATURES.md` ships deliberately. The operator's constraint on the
pdfce builds was *"so I can try it out while you are working"*, and
"try it out" is answerable only if the operator knows what is finished.
Here that matters more than it did there, because this build is a shell
mid-rebuild: without the feature list, a missing Measure tab reads as a
bug rather than as a row that is not ticked yet.

``userdata/`` is deliberately NOT created, for the same reason as pdfce's
packager: the app makes it at first run, so "replace the folder" stays a
safe update procedure precisely because payload and state are
distinguishable.

TWO IDENTITIES, BECAUSE THERE ARE TWO SOURCES
=============================================

pdfce's packager names a build after one commit. This one cannot, and
the difference is not cosmetic — **this binary is built from two trees**:

* the **engine**, `D:\\Dev\\pdfce`, which another session edits live; and
* the **shell**, this workspace.

Both are now git repositories (this one since `2a504ef`, 2026-08-13), so
the name carries a short HEAD for each: ``<engine>-<shell>``.

`source_digest()` survives that, and the reason is specific to how this
project works. Commits here are taken at milestones while **several
agents write concurrently**, so the working tree is dirty far more often
than not — and for a dirty tree the commit hash names the last
checkpoint, not what was compiled. The digest names what was compiled.
It cannot say *what* the code was, only whether two builds were built
from identical bytes, but that is the question a bug report actually
asks: *"is this the build I was running?"*

So they answer different questions and both are recorded. The commit
goes in the folder name; the digest goes in `BUILD-INFO.txt`, and is
appended to the name too when the shell tree is dirty, because that is
exactly the case where the commit alone is not an identity.

THE `-enginedirty` SUFFIX IS LOAD-BEARING
=========================================

`D:\\Dev\\pdfce` is read-only *to this project*, not to its own session,
which means the engine tree can and does move underneath a build. If it
carried uncommitted changes under `crates/`, the linked engine is **not**
the commit in the folder name, and the name would otherwise be a claim
the operator could reasonably rely on and that is false.

The test is deliberately narrow, copied from pdfce's packager and for the
reason recorded there: changes under `docs/`, `fixtures/` and `.claude/`
cannot reach a compiler, so a package built while a documentation agent
was writing is still exactly the named commit. Flagging those produces a
warning that fires when nothing is wrong, and a warning that fires when
nothing is wrong is one that gets ignored when something is. Non-build
changes are still REPORTED in `BUILD-INFO.txt`, just not as a claim about
the payload.

THE NAME MUST NOT START WITH ``pdfce-``
=======================================

`D:\\Dev\\pdfce\\tools\\package-portable.py` finds its previous build with
``dest.glob("pdfce-*")`` and reads that folder's `BUILD-INFO.txt` to pick
the commit its changelog diffs against. A build of THIS project named
`pdfce-gui-2026...` would match that glob, and pdfce's next package would
diff its history against a commit hash belonging to a different tree —
producing a silently wrong changelog in a file whose entire purpose is to
tell the operator what changed.

`pdfcegui-` does not match `pdfce-*` (the glob needs a literal hyphen at
that position). One absent hyphen is the whole safeguard, and a safeguard
that thin cannot rest on a reader noticing it — so ``--self-test``
asserts it against a real temporary directory and pdfce's own glob
string, following the self-test convention `tools/gates/check-ui-strings.sh`
established in this project after a gate shipped that could not catch its
own bug.

EXIT CODES
==========

``0`` build written; ``1`` a prerequisite is missing (no cargo, no engine
tree, no binary after a build attempt, or `--verify` failed); ``2`` the
destination exists and is non-empty, which should be impossible given the
timestamp and means something else is writing there.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Windows consoles default to a code page that cannot encode this file's
# arrows and dashes; see the same block in pdfce's packager and in the
# Python gates.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO = Path(__file__).resolve().parent.parent
ENGINE = Path("D:/Dev/pdfce")
DEFAULT_DEST = Path("D:/builds")

#: Payload files copied verbatim from the repo root, in the order they are
#: listed in `BUILD-INFO.txt`. Deliberate rather than alphabetical: licence
#: first, then the third-party notice that belongs beside it, then the two
#: documents an operator opens.
#:
#: ★ `THIRD_PARTY_LICENSES.md` joined this list on 2026-08-14 and is not
#: optional. It is generated by `cargo-about` from `Cargo.lock`, and its
#: hand-written epilogue carries the licences of the data and font assets the
#: engine embeds — assets `cargo-about` cannot see and that ship inside
#: `pdfce-gui.exe` regardless. A notice file that exists in the repository and
#: not in this list reaches nobody, and looks exactly like one that does, so
#: `tools/gates/check-shipped-assets.py` reads THIS LIST and fails if the
#: notice is missing from it.
PAYLOAD_DOCS = ["LICENSE", "THIRD_PARTY_LICENSES.md", "README.md", "FEATURES.md"]

#: Asset directories copied WHOLE into the portable folder, as
#: `(source relative to the ENGINE tree, destination relative to the package)`.
#:
#: ★ ONE ENTRY, ADDED 2026-08-14 WITH THE OCR FEATURE.
#:
#: Some assets cannot be linked into the executable and have to travel beside
#: it as loose files. The `ocrs` OCR model weights are that case:
#: `pdfce_core::ocr::models::resolve_model_dir` looks for a `models/<engine>`
#: directory beside the running executable, so `pdfce-gui.exe` can only find
#: them if the packager put them there. They are not `include_bytes!`d by any
#: crate and cannot be — twelve megabytes compiled into the binary would be
#: paid by every operator whether or not they ever OCR anything, and would put
#: a CC-BY-SA-4.0 work inside an artifact whose licence file says MIT with no
#: way for a recipient to separate the two.
#:
#: WHAT THE ENTRY BELOW SHIPS: 12,240,008 bytes over two `.rten` files —
#: `text-detection.rten` (2,523,564 B) and `text-rec-checkpoint.rten`
#: (9,716,444 B) — by **Robert Knight**, from
#: <https://huggingface.co/robertknight/ocrs>, licensed **CC-BY-SA-4.0**,
#: BYTE-IDENTICAL to the upstream artifacts (only the filenames are shortened,
#: upstream carrying a content-addressed suffix). Every one of those facts is
#: recorded, with per-file SHA-256 hashes, in that directory's own
#: `PROVENANCE.md` in the engine tree, and none of them should be restated
#: from memory anywhere: there is **no version number**, so the hash is the
#: identity.
#:
#: The operator accepted them into this MIT package on 2026-08-14 —
#: *"yes ship that model in the mit repo with proper credit."*
#:
#: ★ THE COUPLING, WHICH IS THE POINT AND NOT AN OBSTACLE.
#: `tools/gates/check-shipped-assets.py` cross-checks this list against its own
#: register of redistributed engine assets, so this line cannot exist alone:
#: the gate fails until `about.hbs` (the notice that ships) and
#: `crates/pdfce-gui/src/text/about.rs` (the About dialog) both carry the
#: attribution, and it fails in the other direction too if the source
#: directory ever disappears from the engine tree. Without this list the copy
#: would have arrived as an inline `shutil.copytree` somewhere in `main`,
#: invisible to any gate — which is precisely how an obligation goes missing
#: without anyone deciding to drop it.
#:
#: `copy_asset_dirs` drops `PROVENANCE.md` on the way in, deliberately: the
#: operator's copy of that information is `THIRD_PARTY_LICENSES.md` at the top
#: level, and two licence records in one package are two things to keep in
#: step.
#:
#: Sources are in the ENGINE tree because that is where the assets are
#: maintained; this project holds `D:\\Dev\\pdfce` READ-ONLY and only ever
#: copies out of it.
PAYLOAD_ASSET_DIRS: list[tuple[str, str]] = [
    ("crates/pdfce-core/assets/models/ocrs", "models/ocrs"),
]

#: The one shipped binary. Unlike pdfce's packager there is no CLI here:
#: `pdfce-cli` is a member of the ENGINE workspace, and building it would
#: mean invoking cargo inside `D:\Dev\pdfce` — a write to a tree this
#: project holds read-only (it would create/refresh `target/`). Operators
#: who want the CLI take it from a pdfce build, which is where it is
#: maintained.
BINARIES = ["pdfce-gui.exe"]

#: Prefixes under the ENGINE tree that can reach a compiler. Generous on
#: purpose: under-reporting here produces the false reassurance the
#: `-enginedirty` suffix exists to prevent, while over-reporting costs
#: only an unnecessary suffix.
BUILD_AFFECTING = (
    "crates/",
    "Cargo.toml",
    "Cargo.lock",
    "rust-toolchain",
    ".cargo/",
    "build.rs",
)

#: What `source_digest()` hashes. Mirrors BUILD_AFFECTING for this tree.
#: `tools/` is EXCLUDED — this file lives there, and a packager edit is
#: not a change to the shipped program. `tools/ui-verify` is a workspace
#: member but produces no shipped artifact.
SOURCE_GLOBS = ("crates/**/*.rs", "crates/**/Cargo.toml")
SOURCE_FILES = ("Cargo.toml", "Cargo.lock")


def git(*args: str, cwd: Path = ENGINE) -> str:
    """Run a git command in `cwd` and return its stripped stdout.

    Defaults to the ENGINE tree because that is the identity most calls
    below want; pass `cwd=REPO` for the shell's own repository.

    `encoding="utf-8"` is not optional, and the reason is recorded in
    pdfce's packager: `text=True` alone decodes with the LOCALE codec,
    cp1252 on this machine, and pdfce's commit subjects are full of
    em-dashes — so a changelog rendered `Pass 54.1 â€” a group can be
    deleted`. `errors="replace"` so a stray non-UTF-8 byte in some future
    commit degrades one character instead of failing a build.
    """
    return subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    ).stdout.strip()


def locked_engine_rev(repo: Path) -> str | None:
    """The engine revision `Cargo.lock` says this build actually links.

    **This, not the engine tree's HEAD, is the engine's identity.** The
    distinction became real on 2026-08-18, when `pdfce-gui` moved from a
    path dependency to `git = "file:///D:/Dev/pdfce", branch = "main"`: a
    path dependency compiles the working tree, a git dependency compiles a
    committed revision out of `~/.cargo/git/`, and the two can differ by
    any number of commits plus whatever is uncommitted.

    `Cargo.lock` is the only artefact that records what was compiled, and
    it moves only on `cargo update`. So committing in the engine — or
    editing it, or checking out another branch — does not change this
    build, and reading HEAD would credit the binary with commits it does
    not contain.

    Parsed with a regex rather than a TOML library on purpose: this script
    has no third-party dependencies and gains none for one line. The shape
    it matches is Cargo's own and is stable —

        [[package]]
        name = "pdfce-core"
        version = "0.5.3"
        source = "git+file:///D:/Dev/pdfce?branch=main#13456637..."

    Returns `None` rather than raising when the lock has no such entry,
    which is the state a **path** dependency produces (path deps record no
    `source` at all). The caller reports "unknown" and the build still
    happens: refusing to package because an identity could not be read
    would be this script deciding it knows better than the operator who
    ran it.
    """
    lock = repo / "Cargo.lock"
    if not lock.is_file():
        return None
    text = lock.read_text(encoding="utf-8", errors="replace")
    # Non-greedy across the entry so `name` and `source` are matched within
    # the SAME `[[package]]` block. A greedy match would happily pair
    # `pdfce-core`'s name with some later package's source.
    match = re.search(
        r'\[\[package\]\]\s*\nname = "pdfce-core"\n.*?source = "git\+[^"]*#([0-9a-f]{7,40})"',
        text,
        re.DOTALL,
    )
    return match.group(1) if match else None


def source_digest(repo: Path) -> str:
    """A 12-hex digest identifying this workspace's build-affecting source.

    Stands in for the commit hash this project does not have. The contract
    is narrow and worth stating exactly, because a digest invites more
    trust than it earns: **identical digests mean identical source; a
    different digest means the source differs, somewhere.** It cannot say
    what differs, and it is not a version — 12 hex digits sort
    meaninglessly.

    Determinism is the whole value, so both inputs are normalised:

    * **Paths** are relative and forward-slashed, so the digest does not
      change if the workspace is moved or built from a different shell.
    * **Order** is sorted by that relative path, because `Path.glob` order
      is filesystem-dependent — the same tree on a different volume would
      otherwise digest differently.

    The path is hashed alongside the bytes so that RENAMING a file changes
    the digest. Hashing contents alone would call a rename a no-op, and a
    rename absolutely changes the program.
    """
    h = hashlib.sha256()
    paths: set[Path] = set()
    for pattern in SOURCE_GLOBS:
        paths.update(p for p in repo.glob(pattern) if p.is_file())
    for name in SOURCE_FILES:
        p = repo / name
        if p.is_file():
            paths.add(p)
    for p in sorted(paths, key=lambda q: q.relative_to(repo).as_posix()):
        h.update(p.relative_to(repo).as_posix().encode("utf-8"))
        h.update(b"\0")
        h.update(p.read_bytes())
    return h.hexdigest()[:12]


def path_of(line: str) -> str:
    """The path out of one `git status --porcelain` line.

    `XY <path>`, or `XY <old> -> <new>` for a rename; the destination is
    what exists on disk now.

    Parsed with a regex rather than `line[3:]`, and the reason is a bug
    pdfce's packager hit: the status field is two columns and EITHER may
    be a space, while `git()` strips its output — which removes the
    leading space from the first line only. A fixed offset therefore ate
    one character of exactly one path per run, printing
    `claude/agent-memory/...` for `.claude/...`. One wrong entry in a list
    of correct ones is the worst version of this bug: the list looks
    right, so the reader trusts the entry that is not, and a path that
    does not exist reads as a deleted file rather than as a parse error.
    """
    m = re.match(r"^\s*\S{1,2}\s+(.*)$", line)
    if not m:
        return ""
    return m.group(1).split(" -> ")[-1].strip().strip('"')


def previous_build(dest: Path) -> tuple[str, str, str] | None:
    """`(engine_commit, shell_commit, source_digest)` of the most recent
    build of THIS project in `dest`, or `None`.

    `shell_commit` is `""` for builds packaged before this workspace was
    put under git (2026-08-13), whose `BUILD-INFO.txt` has no `Shell:`
    line. Callers must treat it as "no baseline" rather than as a ref —
    which is why the changelog below verifies every ref it is handed.

    Read out of that build's own `BUILD-INFO.txt` rather than parsed from
    the folder name: the name is for humans and can be renamed, the file
    is the record.

    The glob is `pdfcegui-*`, which excludes pdfce's own builds. Reading
    one of those would produce a changelog diffing this tree's history
    against a commit from a build of a different program.
    """
    builds = sorted(
        (p for p in dest.glob("pdfcegui-*") if p.is_dir()),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    for b in builds:
        info = b / "BUILD-INFO.txt"
        if not info.is_file():
            continue
        engine = shell = src = ""
        for line in info.read_text(encoding="utf-8", errors="replace").splitlines():
            # `Shell source digest:` is matched BEFORE `Shell:` — the
            # latter is a prefix of nothing here, but `startswith` order
            # is the kind of thing that quietly stops being true when a
            # label is renamed, so the specific one goes first.
            if line.startswith("Shell source digest:"):
                src = line.split(":", 1)[1].strip().split()[0]
            elif line.startswith("Engine:"):
                engine = line.split(":", 1)[1].strip().split()[0]
            elif line.startswith("Shell:"):
                shell = line.split(":", 1)[1].strip().split()[0]
        if engine:
            return engine, shell, src
    return None


def copy_asset_dirs(out: Path, engine: Path) -> tuple[list[str], list[str]]:
    """Copy every `PAYLOAD_ASSET_DIRS` entry into the package.

    Returns `(copied, missing)` — destination paths that were written, and
    source paths that were declared and are not there.

    `engine` is a parameter rather than the module constant so `--self-test`
    can exercise this against a synthetic tree. That matters more than it
    looks: this list is empty today, so without a self-test the copy loop
    would ship **never having run once**, and the first time it did would be
    the day someone added a 12 MB licensed asset to a release. A code path
    that has never executed is not code that works; it is code that compiles.

    `dirs_exist_ok=False` on purpose. The destination is a folder this run
    just created under a timestamped name, so an existing directory there
    means something else is writing into the same package, and merging two
    writers' asset trees would produce a folder neither of them intended.
    """
    copied: list[str] = []
    missing: list[str] = []
    for source, dest in PAYLOAD_ASSET_DIRS:
        src = engine / source
        if not src.is_dir():
            missing.append(source)
            continue
        target = out / dest
        target.parent.mkdir(parents=True, exist_ok=True)
        # `ignore` drops the provenance note: it documents the asset for a
        # reader of the SOURCE TREE, and the operator's copy of that
        # information is `THIRD_PARTY_LICENSES.md`, which ships at the top
        # level where they will actually find it. Copying it here as well
        # would put a second, differently-worded licence record inside a data
        # folder — and two records are two things to keep in step.
        shutil.copytree(src, target, ignore=shutil.ignore_patterns("PROVENANCE.md"))
        copied.append(dest)
    return copied, missing


def run_verification(repo: Path) -> tuple[bool, str]:
    """Run the test suite and the CI gates; return `(ok, report)`.

    Opt-in via `--verify` rather than always-on, because a full workspace
    test run is minutes and the common case is packaging a build the
    session just verified.

    But when it is NOT run, `BUILD-INFO.txt` says so in those words. An
    omitted verification line would read as "nothing to report", which is
    the opposite of the truth: it means nobody checked. This project's
    whole verification stance is that a passing test is not evidence an
    operator can reach a feature (`FEATURES.md`), so a build that quietly
    implies it was verified is exactly the wrong artifact to ship.
    """
    # The spawned shell may not inherit cargo's directory.
    #
    # `tools/gates/run-all.sh` runs `cargo fmt` and `cargo clippy`. A bash
    # spawned from here is neither a login nor an interactive shell, so it
    # never reads the profile that puts `~/.cargo/bin` on PATH — and the gate
    # runner then SKIPs both, which makes it exit 3, which fails `--verify`
    # while every gate that actually ran was clean.
    #
    # ★ Honest provenance, because the next reader deserves it: this was
    # OBSERVED under a nested, sandboxed shell where `python` and `rustc`
    # were invisible too, so the sandbox — not the profile — was that
    # instance's cause, and this prepend did NOT fix it there. It is kept
    # because the non-login-shell case is real, independent, and costs two
    # lines. It has not been verified against that case.
    #
    # The half that WAS verified and fixed is `run-all.sh`'s message: it
    # reported `cargo: command not found` as "the workspace does not
    # currently load", which was flatly false and pointed the reader at the
    # one place the problem was not.
    env = os.environ.copy()
    cargo = shutil.which("cargo")
    if cargo:
        env["PATH"] = str(Path(cargo).parent) + os.pathsep + env.get("PATH", "")

    lines = []
    ok = True
    for label, cmd in (
        ("tests", ["cargo", "test", "--workspace", "--quiet"]),
        ("gates", ["bash", "tools/gates/run-all.sh"]),
    ):
        print(f"package-portable: {label} ...")
        r = subprocess.run(
            cmd,
            cwd=repo,
            env=env,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
        )
        passed = r.returncode == 0
        ok = ok and passed
        tail = (r.stdout or r.stderr or "").strip().splitlines()[-3:]
        lines.append(f"  {label}: {'PASS' if passed else 'FAIL'}")
        lines.extend(f"    {t}" for t in tail)
    return ok, "\n".join(lines)


def self_test() -> int:
    """Assert the two invariants that are otherwise invisible.

    Both are properties nothing else would catch. A wrong folder name
    still packages successfully and still runs; the damage lands in a
    DIFFERENT project's changelog, days later. A non-deterministic digest
    still produces a name; it just quietly stops answering the one
    question it exists to answer. Neither failure mode announces itself,
    which is precisely why they are asserted rather than reasoned about.
    """
    import tempfile

    failures: list[str] = []

    # 1. The name must not be picked up by pdfce's own packager. Asserted
    #    against a real directory and pdfce's literal glob string, not by
    #    comparing prefixes — the whole point is to test the thing that
    #    actually runs over there.
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        (root / "pdfcegui-20260813-1200-abc1234-0123456789ab").mkdir()
        (root / "pdfce-20260813-1200-abc1234").mkdir()
        caught = sorted(p.name for p in root.glob("pdfce-*") if p.is_dir())
        if caught != ["pdfce-20260813-1200-abc1234"]:
            failures.append(
                "a pdfceGUI build name matches pdfce's `pdfce-*` glob; "
                f"its packager would read {caught} as its own previous build"
            )
        mine = sorted(p.name for p in root.glob("pdfcegui-*") if p.is_dir())
        if len(mine) != 1:
            failures.append(f"`pdfcegui-*` did not match exactly this project's build: {mine}")

    # 2. The digest must be stable across repeated calls on an unchanged
    #    tree, and must move when a byte does. Run against the real
    #    workspace, because a synthetic tree would not exercise the glob
    #    patterns that decide what is hashed in the first place.
    a = source_digest(REPO)
    b = source_digest(REPO)
    if a != b:
        failures.append(f"source_digest is not deterministic: {a} != {b}")
    if len(a) != 12:
        failures.append(f"source_digest returned {len(a)} chars, expected 12")
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        (root / "crates" / "x" / "src").mkdir(parents=True)
        f = root / "crates" / "x" / "src" / "lib.rs"
        f.write_text("fn a() {}", encoding="utf-8")
        before = source_digest(root)
        f.write_text("fn b() {}", encoding="utf-8")
        if source_digest(root) == before:
            failures.append("source_digest did not change when a source byte changed")
        f.rename(root / "crates" / "x" / "src" / "renamed.rs")
        if source_digest(root) == before:
            pass  # already differs; the rename check below is the real one
        moved = source_digest(root)
        (root / "crates" / "x" / "src" / "renamed.rs").rename(f)
        if source_digest(root) == moved:
            failures.append("source_digest ignored a rename; it must hash paths too")

    # 3. The asset-directory copy works, and reports a missing source rather
    #    than skipping it.
    #
    #    ★ This exists because `PAYLOAD_ASSET_DIRS` is EMPTY. An empty list
    #    means `copy_asset_dirs` never runs in a real package, so without this
    #    the first execution of that loop would be the day somebody added a
    #    12 MB licensed asset to a release — which is the worst possible day
    #    to discover a typo in a `copytree` call. The engine tree is
    #    synthesised here rather than read, so the test neither touches
    #    `D:\\Dev\\pdfce` nor depends on it being mounted.
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        engine = root / "engine"
        (engine / "crates" / "demo" / "assets" / "models").mkdir(parents=True)
        weights = engine / "crates" / "demo" / "assets" / "models" / "weights.bin"
        weights.write_bytes(b"\x01\x02\x03")
        (engine / "crates" / "demo" / "assets" / "models" / "PROVENANCE.md").write_text(
            "terms", encoding="utf-8"
        )
        out = root / "package"
        out.mkdir()

        global PAYLOAD_ASSET_DIRS  # noqa: PLW0603 — restored below
        saved = PAYLOAD_ASSET_DIRS
        try:
            PAYLOAD_ASSET_DIRS = [("crates/demo/assets/models", "models/demo")]
            copied, missing = copy_asset_dirs(out, engine)
            if missing:
                failures.append(f"copy_asset_dirs reported a present source as missing: {missing}")
            if copied != ["models/demo"]:
                failures.append(f"copy_asset_dirs copied {copied}, expected ['models/demo']")
            if not (out / "models" / "demo" / "weights.bin").is_file():
                failures.append("copy_asset_dirs did not write the asset into the package")
            if (out / "models" / "demo" / "PROVENANCE.md").exists():
                failures.append(
                    "copy_asset_dirs shipped PROVENANCE.md — the operator's copy of that "
                    "information is THIRD_PARTY_LICENSES.md at the top level"
                )

            PAYLOAD_ASSET_DIRS = [("crates/demo/assets/gone", "models/gone")]
            _copied, missing = copy_asset_dirs(root / "package2", engine)
            if missing != ["crates/demo/assets/gone"]:
                failures.append(
                    "a declared asset directory that does not exist was NOT reported; "
                    "the package would have shipped an attribution for absent files"
                )
        finally:
            PAYLOAD_ASSET_DIRS = saved

    for msg in failures:
        print(f"package-portable --self-test: FAIL — {msg}")
    if failures:
        return 1
    print(
        "package-portable --self-test: 3 invariants hold "
        "(name collision, digest, asset copy)."
    )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--dest",
        type=Path,
        default=DEFAULT_DEST,
        help="destination root (default: D:/builds)",
    )
    ap.add_argument(
        "--no-build",
        action="store_true",
        help="package the existing target/release binary without rebuilding",
    )
    ap.add_argument(
        "--verify",
        action="store_true",
        help="run the workspace tests and the CI gates, and record the result",
    )
    ap.add_argument(
        "--note",
        default="",
        help="one-line summary of what this milestone added, for BUILD-INFO.txt",
    )
    ap.add_argument(
        "--self-test",
        action="store_true",
        help="assert this script's own invariants and exit; packages nothing",
    )
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    if not (REPO / "Cargo.toml").is_file():
        print(f"package-portable: {REPO} is not the pdfceGUI workspace root.")
        return 1
    if not (ENGINE / "Cargo.toml").is_file():
        # Not a nicety. The path dependencies point here; without it the
        # build below fails with a cargo error about a missing manifest
        # that does not mention why the path matters.
        print(f"package-portable: the engine tree {ENGINE} is missing.")
        print("  crates/pdfce-gui depends on pdfce-core and pdfce-render by path.")
        return 1

    # --- identity, before anything is built --------------------------------
    #
    # Computed for BOTH trees with the same three questions: what commit,
    # what did it say, and does the tree carry changes that can reach a
    # compiler. `dirty_of()` is shared rather than duplicated because the
    # narrow definition of "dirty" is the load-bearing part, and two
    # copies of it would drift.
    def dirty_of(cwd: Path) -> tuple[list[str], list[str]]:
        changed = [
            path_of(l) for l in git("status", "--porcelain", cwd=cwd).splitlines() if l.strip()
        ]
        build = [p for p in changed if p.startswith(BUILD_AFFECTING)]
        return build, [p for p in changed if p not in build]

    # ★★ THE ENGINE'S IDENTITY IS THE LOCKED REVISION, NOT THE TREE'S HEAD —
    # rewritten 2026-08-18 when the dependency form changed.
    #
    # This used to read `git rev-parse HEAD` in the engine tree, which was
    # correct while `pdfce-gui` took the engine by PATH: a path dependency
    # compiles the working tree, so the tree's HEAD (plus a dirty flag) was
    # what got linked.
    #
    # It is now `git = "file:///D:/Dev/pdfce", branch = "main"`. Cargo clones
    # that repository and builds a **specific commit** out of `~/.cargo/git/`,
    # so the working tree is not compiled at all. Two consequences, and both
    # would have made the old code lie:
    #
    #   1. **A dirty engine worktree can no longer reach the binary.** The
    #      `-enginedirty` suffix would have fired on a build it does not
    #      describe — and this script's own docstring says a warning that
    #      fires when nothing is wrong is one that gets ignored when
    #      something is.
    #   2. **HEAD can be AHEAD of what was linked.** `Cargo.lock` pins a
    #      revision and only `cargo update` moves it, so committing in the
    #      engine does not change this build. Naming HEAD would have credited
    #      the binary with commits it does not contain, which is the more
    #      dangerous error of the two.
    #
    # So the identity is read from `Cargo.lock`, which is the only artefact
    # that records what was actually compiled. `git log` in the engine tree is
    # still used to turn that revision into a subject line, because a hash
    # with no sentence beside it tells the operator nothing.
    engine_locked = locked_engine_rev(REPO)
    engine_short = (engine_locked or "unknown")[:7]
    engine_subject = (
        git("log", "-1", "--format=%s", engine_locked) if engine_locked else ""
    )
    # Reported, never in the name: the tree may be mid-edit by the session
    # that owns it, and that is now simply none of this build's business.
    dirty_build, dirty_other = dirty_of(ENGINE)
    engine_head = git("rev-parse", "--short", "HEAD") or "unknown"
    engine_behind = (
        git("rev-list", "--count", f"{engine_locked}..HEAD") if engine_locked else ""
    )

    shell_short = git("rev-parse", "--short", "HEAD", cwd=REPO) or "unknown"
    shell_subject = git("log", "-1", "--format=%s", cwd=REPO)
    shell_dirty_build, shell_dirty_other = dirty_of(REPO)
    src = source_digest(REPO)

    stamp = datetime.now().strftime("%Y%m%d-%H%M")
    # The digest joins the NAME only when the shell tree is dirty. On a
    # clean tree the commit already identifies the bytes, and a
    # permanently-appended 12-hex string would be noise in every folder
    # name; on a dirty tree the commit identifies the last checkpoint and
    # nothing else, so the digest is the only thing distinguishing this
    # build from the next one taken thirty seconds later.
    name = f"pdfcegui-{stamp}-{engine_short}-{shell_short}"
    if shell_dirty_build:
        name += f"-dirty-{src}"
    # ★ No `-enginedirty`. It was removed on 2026-08-18 with the dependency
    # change above: the engine is built from a committed revision out of
    # cargo's git cache, so its working tree cannot reach this binary and a
    # suffix claiming otherwise would be false. The tree's state is still
    # REPORTED in `BUILD-INFO.txt` — it is useful context about the
    # repository — it is just no longer a claim about the payload.
    out = args.dest / name

    if out.exists() and any(out.iterdir()):
        print(f"package-portable: {out} already exists and is not empty.")
        return 2

    # --- verify, BEFORE building -------------------------------------------
    #
    # Order is deliberate: a failed verification should cost the operator
    # nothing and leave no folder behind. Verifying after packaging would
    # produce a written build that the same run then declares unfit.
    verification = "  not run for this package (pass --verify to run it)"
    if args.verify:
        ok, verification = run_verification(REPO)
        if not ok:
            print("\npackage-portable: verification failed; nothing packaged.")
            print(verification)
            return 1

    # --- build --------------------------------------------------------------
    if not args.no_build:
        print("package-portable: cargo build --release -p pdfce-gui ...")
        rc = subprocess.run(
            ["cargo", "build", "--release", "-p", "pdfce-gui"],
            cwd=REPO,
            check=False,
        ).returncode
        if rc != 0:
            print("package-portable: the release build failed; nothing packaged.")
            return 1

    rel = REPO / "target" / "release"
    missing = [b for b in BINARIES if not (rel / b).is_file()]
    if missing:
        print(f"package-portable: missing binaries in {rel}: {', '.join(missing)}")
        return 1

    # --- assemble -----------------------------------------------------------
    out.mkdir(parents=True, exist_ok=True)
    for b in BINARIES:
        shutil.copy2(rel / b, out / b)
    copied_docs = []
    for d in PAYLOAD_DOCS:
        s = REPO / d
        if s.is_file():
            shutil.copy2(s, out / d)
            copied_docs.append(d)
        else:
            print(f"package-portable: WARNING — {d} not found at the workspace root")

    # --- asset directories that must travel as loose files ------------------
    #
    # A MISSING SOURCE IS FATAL, not a warning. The two things in this list's
    # future are licensed assets whose absence would be silent: the package
    # would build, the operator would get a program that reports "no OCR
    # models" from a folder that was supposed to contain them, and the
    # attribution in `THIRD_PARTY_LICENSES.md` would be describing files that
    # are not there. Every other payload item degrades to a warning because
    # `README.md` going missing costs a reader a document; this costs the
    # package its correctness in both directions at once.
    copied_assets, missing_assets = copy_asset_dirs(out, ENGINE)
    if missing_assets:
        print("package-portable: declared asset directories are missing from the engine tree:")
        for m in missing_assets:
            print(f"  {m}")
        print("  Nothing was packaged. PAYLOAD_ASSET_DIRS names files this build")
        print("  is obliged to ship AND to attribute; shipping the attribution")
        print("  without the files would make THIRD_PARTY_LICENSES.md describe")
        print("  something the operator does not have.")
        shutil.rmtree(out, ignore_errors=True)
        return 1

    # --- what changed since the last build ----------------------------------
    def changelog(cwd: Path, since: str | None, label: str) -> str:
        """Commits in `cwd` since the previous build, formatted for the file.

        `since` may name a commit this tree does not contain — a build
        packaged before a history rewrite, or a `BUILD-INFO.txt` copied
        between machines. `git log bad..HEAD` writes to stderr and returns
        nothing, and `git()` returns only stdout, so that failure would
        otherwise render as a confident, empty "(none)": a claim that
        nothing changed, which is the worst available answer. Verifying
        the ref first turns it into a stated fallback.
        """
        if since:
            # `git cat-file -e` answers through its EXIT CODE and prints
            # nothing, so this cannot go through `git()` — that helper
            # returns stdout, which is empty either way.
            exists = subprocess.run(
                ["git", "cat-file", "-e", f"{since}^{{commit}}"],
                cwd=cwd,
                capture_output=True,
                check=False,
            ).returncode == 0
            if not exists:
                label += (
                    "\n  (the previous build's commit is not in this tree;"
                    " showing recent history instead)"
                )
                since = None
        if since:
            out_ = git("log", "--oneline", "--no-decorate", f"{since}..HEAD", cwd=cwd)
        else:
            out_ = git("log", "--oneline", "--no-decorate", "-10", cwd=cwd)
        body = "\n".join(f"  {l}" for l in out_.splitlines()) if out_ else "  (none)"
        return f"{label}\n{body}"

    prev = previous_build(args.dest)
    if prev:
        prev_engine, prev_shell, prev_src = prev
        engine_log = changelog(
            ENGINE, prev_engine, f"Engine commits since the previous build ({prev_engine}):"
        )
        shell_log = changelog(
            REPO, prev_shell or None, f"Shell commits since the previous build ({prev_shell}):"
        )
        digest_line = (
            "  Source digest UNCHANGED since the previous build — this is the\n"
            "  same program, however the commits read."
            if prev_src == src
            else f"  Source digest changed: {prev_src} -> {src}"
        )
    else:
        engine_log = changelog(ENGINE, None, "Recent engine commits (no previous build to diff):")
        shell_log = changelog(REPO, None, "Recent shell commits (no previous build to diff):")
        digest_line = "  No previous build to compare the source digest against."

    warn = ""
    if shell_dirty_build:
        listed = "\n".join(f"  {q}" for q in shell_dirty_build[:10])
        more = "\n  ..." if len(shell_dirty_build) > 10 else ""
        warn += (
            "\n*** THE SHELL WAS BUILT FROM AN UNCOMMITTED WORKING TREE ***\n"
            "The shell commit below is the last CHECKPOINT, not what was compiled.\n"
            "Use the source digest to tell this build apart from another; the\n"
            "code itself is in no commit and cannot be recovered from the hash.\n"
            f"{listed}{more}\n"
        )
    # ★ The engine tree's state is CONTEXT now, not a warning about the
    # payload. Since 2026-08-18 the engine is compiled from a committed
    # revision out of cargo's git cache, so nothing uncommitted in
    # D:\Dev\pdfce can reach this binary — see `locked_engine_rev`.
    #
    # It is still reported, because it answers the question an operator
    # actually has when a fix they know landed is not in the build: *is the
    # engine ahead of what I am running?* That question used to be
    # unanswerable and it is the one that cost eighteen images on a real file.
    if dirty_build or dirty_other:
        changed = dirty_build + dirty_other
        listed = "\n".join(f"  {q}" for q in changed[:10])
        more = "\n  ..." if len(changed) > 10 else ""
        warn += (
            "\nEngine tree note: D:\\Dev\\pdfce had uncommitted changes when this was\n"
            "packaged. They are NOT in this binary — the engine is built from the\n"
            "committed revision named below, out of cargo's git cache — so this is\n"
            "context rather than a warning:\n"
            f"{listed}{more}\n"
        )
    if engine_behind and engine_behind not in ("", "0"):
        warn += (
            f"\n*** THE ENGINE HAS MOVED ON: {engine_behind} COMMIT(S) NOT IN THIS BUILD ***\n"
            f"This binary links {engine_short}; D:\\Dev\\pdfce's main is at {engine_head}.\n"
            "Cargo.lock pins the revision and only `cargo update` moves it, so this\n"
            "is deliberate rather than broken. To pick them up:\n"
            "  cargo update -p pdfce-core -p pdfce-render -p pdfce-print\n"
            "Worth checking before investigating any RENDERING complaint as a shell\n"
            "defect: a stale engine pin has already produced exactly that confusion.\n"
        )

    # Hoisted out of the f-string: an expression part may not contain a
    # backslash before Python 3.12, and this machine runs 3.11.
    note_block = f"THIS BUILD\n----------\n{args.note}\n" if args.note else ""

    (out / "BUILD-INFO.txt").write_text(
        f"""pdfceGUI portable build
=======================
{warn}
Built:  {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Engine: {engine_short}  {engine_subject}
        (D:\\Dev\\pdfce, branch {git("rev-parse", "--abbrev-ref", "HEAD")})
Shell:  {shell_short}  {shell_subject}
        (D:\\Dev\\pdfceGUI, branch {git("rev-parse", "--abbrev-ref", "HEAD", cwd=REPO)})
Shell source digest: {src}
        Identifies the BYTES compiled, which the commit above does not when
        the tree is dirty. Two builds with the same digest are the same
        program; a different digest means the source differs, somewhere.

WHAT THIS IS
------------
The NEW pdfce shell, rebuilt from scratch, with pdfce's engine linked in
statically. One executable, no installer, no registry writes, nothing
outside this folder. Run pdfce-gui.exe.

It is not a replacement for a pdfce build yet, and FEATURES.md ships
beside it so you can tell which is which. Measure, redaction, the
settings dialog and text editing still live only in the OLD shell —
install this alongside a pdfce build rather than instead of one.

WHAT TO TRY
-----------
Open a PDF, then: click an object and press Delete; drag a selection;
press Escape mid-drag; switch Read / Review / Edit with Ctrl+1/2/3; drag
a panel to another dock column and restart to confirm the layout came
back. FEATURES.md's first list is the full set that should work.

YOUR SETTINGS LIVE IN THIS FOLDER
---------------------------------
On first run the app creates `userdata/` here. To update, replace the
binary but KEEP `userdata/`.

VERIFICATION
------------
{verification}

{note_block}
{engine_log}

{shell_log}

Source digest:
{digest_line}

Files in this build: {", ".join(BINARIES + copied_docs + [d + "/" for d in copied_assets])}

THIRD-PARTY MATERIAL
--------------------
THIRD_PARTY_LICENSES.md carries the licence of every Rust crate this binary
links, and — in a hand-written epilogue — the licences of the data and font
assets the engine embeds, which no generator can see. The same attributions
are in the program itself: File > pdfce > About pdfce.
""",
        encoding="utf-8",
    )

    total = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
    print(f"\npackage-portable: wrote {out}")
    for f in sorted(out.iterdir()):
        print(f"  {f.name:<26} {f.stat().st_size:>10,} bytes")
    print(f"  {'TOTAL':<26} {total:>10,} bytes")
    if dirty_build:
        print("\n  WARNING: the engine had uncommitted build-affecting changes.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
